version: '2'
services: 
  moodle:
    image: bitnami/moodle:latest
    ports:
      - 7080:8080
      - 7443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - PUID=998
      - PGID=100
      - ALLOW_EMPTY_PASSWORD=yes #only for testing purpose
    volumes:
      - ./moodle_data:/bitnami/moodle
      - 'moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
    volumes:
      - ./mariadb_data:/var/lib/mysql

volumes:
  moodledata:
    driver: local
